version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: products-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d productdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  products-service:
    build: .
    container_name: products-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/productdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      INVENTORY_SERVICE_URL: http://inventory-service:8081
      INVENTORY_API_KEY: inventory-secret-key
    depends_on:
      postgres-db:
        condition: service_healthy
